bin: fix a python3 syntax error and clarify an argparse exception
- previously bin/jsonschema_generator.py would not function under
python3 because missing parentheses around print() arguments

- when running 'python3 bin/jsonschema_generator.py', an AttributeError
exception would be thrown with no helpful explanation ("Namespace object
has no attribute 'func'") so a clause is added to catch it
	- note that in Python 2, if the first positional argument was
ommitted, argparse would print an explanation in english -- this was
changed to just throw an AttributeError with vague explanation in Python 3